CitizenScience/models.py
from CitizenScience import db

#Database setup
class Picture(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(200), nullable=False)
    rank=db.Column(db.Integer, nullable=False)
    def __repr__(self):
        return f"Picture('{self.name}', '{self.rank}')"

CitizenScience/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField


from CitizenScience.models import Picture

class VerifyForm(FlaskForm):
    image_one=StringField('Image One')
    image_two=StringField('Image Two')    
    submit=SubmitField('Submit your choice')

CitizenScience/__init__.py
from flask import Flask, Blueprint
from flask_sqlalchemy import SQLAlchemy

app=Flask(__name__)
app.config['SECRET_KEY']='a5ac97b06027bd65a170f3d5409feeb5'
app.config['SQLALCHEMY_DATABASE_URI']='sqlite:///site.db'
db=SQLAlchemy(app)


from CitizenScience.main.routes import main


app.register_blueprint(main)

CitizenScience/main/routes.py
import os
import re
import secrets
import random
from PIL import Image
from flask import Blueprint, render_template, url_for, request, redirect, flash
from CitizenScience import app, db
from CitizenScience.models import Picture
from CitizenScience.main.forms import VerifyForm


main=Blueprint('main', __name__)


#Use function once....I will get a way to sync

# def save_picture():
#     # Accessing one of the pictures 
#     image_folder=os.path.join(app.root_path, "static/weed_rank_images/")
#     count=0
#     for picture in os.listdir(image_folder):
#         count+=1
#         # Picture on filesystem       
#         #New folder to save reduced file
#         new_picture_path=os.path.join(app.root_path,'static/new_weed_images/')
#         output_size=(500,500)
#         i=Image.open(image_folder+'\\'+picture)
#         i.thumbnail(output_size, Image.ANTIALIAS)
#         i.save(new_picture_path+'\\'+picture)
#         store_pictures=Picture(name=picture, rank=count)
#         #Storing picture information in database
#         db.session.add(store_pictures)
#         db.session.commit()

# save_picture()

# Function to randomise and return 2 distinct pictures
def random_two():
    img=[]
    picture_one=random.choice(Picture.query.all())
    picture_two=random.choice(Picture.query.all())
    if picture_one == picture_two:
        random_two()
    else:
        img.append(picture_one)
        img.append(picture_two)
    
    return img

#This route reduces the size of picture files, copy them into another folder and display on webpage
@main.route('/', methods=['POST', 'GET']) 
@main.route('/home', methods=['POST', 'GET'])
def home(): 
    forms=VerifyForm()  
    # Use only save_picture function when loading a new set of pictures... I will fix this later
    # save_picture()

   
    if request.method=='GET':
        global select_two_images
        select_two_images=random_two()
       
    elif request.method=='POST':
        #name1=request.form.getvalue('image_file[0]')
        selected_option=request.form.get('image_file')
     
        try:

            # print(selected_option)
            selected_rank=re.findall('\s\'([0-9]+)',selected_option)
            #print(selected_rank)
            selected_rank=''.join(map(str,selected_rank))

            print(select_two_images)

            presented_options=list(map(int,re.findall('\s\'([0-9]+)',str(select_two_images))))
            #print(int(min(presented_options)))
            #print(int(max(presented_options)))

            if min(presented_options) < int(selected_rank):
                change_to_lower=Picture.query.filter_by(rank=int(selected_rank)).first()            
                change_to_higher=Picture.query.filter_by(rank=int(min(presented_options))).first()

                change_to_lower.rank=min(presented_options) 
                print(change_to_lower.rank)
                change_to_higher.rank=max(presented_options)  
                         
                db.session.commit() 
            
            return redirect(url_for('main.submit'))  

        except:
            flash('Kindly select a picture!', 'info')
                   
   
    return render_template('home.html', image_file=select_two_images, form=forms)

# 

@main.route('/submit')
def submit():
    return render_template('submit.html') 



# from CitizenScience import db 
# from CitizenScience.models  import Picture 
# Picture.query.all()

CitizenScience/templates/home.html
{%extends "layout.html"%}
{%block content%}

<h2 class="article-title">Kindly select a picture that has most weed</h2>
<form method="POST" action="" >
    {{form.hidden_tag()}}  
    <div class="row content-section">
        <div class="row">
            <div class="column">
                <div class="custom-control custom-radio image-checkbox">
                    <input type="radio" class="custom-control-input" id="ck2a" value="{{image_file[0]}}" name="image_file">
                    <label class="custom-control-label" for="ck2a">
                        <img src="{{url_for('static', filename='new_weed_images/'+ image_file[0].name)}}" alt="#" class="img-fluid">
                    </label>
                </div>
            </div>        
            <div class="column">
                <div class="custom-control custom-radio image-checkbox">
                    <input type="radio" class="custom-control-input" id="ck2b" value="{{image_file[1]}}" name="image_file">
                    <label class="custom-control-label" for="ck2b">
                        <img src="{{url_for('static', filename='new_weed_images/'+ image_file[1].name)}}" alt="#" class="img-fluid">
                    </label>
                </div>
            </div>             
        </div>
        <div class=' mt-3 form-group btn btn-outline-info'>
            <input type="submit">
        </div>
    </div>
 
     
</form>
<p>{{image_file[0]}},{{image_file[1]}}</p>
{%endblock content%}

CitizenScience/templates/layout.html
<html>

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" type='text/css' href="{{url_for('static', filename='main.css')}}">

  {%if title%}
  <title>Citizen Science-{{title}}</title>
  {%else%}
  <title>Citizen Science</title>
  {%endif%}
</head>

<body>
  <header class="site-header">
    <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
      <div class="container">
        <a class="navbar-brand mr-4" href="{{url_for('main.home')}}">Citizen Science Project</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
          aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      </div>
    </nav>
  </header>
  <main role="main" class="container">
    <div class="row">
      <div class="col-md-8">
        {%with messages=get_flashed_messages(with_categories=true)%}
        {%if messages%}
        {%for category, message in messages%}
        <div class="alert alert-{{category}}">
          {{message}}
        </div>
        {%endfor%}
        {%endif%}
        {%endwith%}
        {% block content %}{% endblock %}
      </div>
      

    </div>
  </main>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
    crossorigin="anonymous"></script>

</body>

</html>

CitizenScience/templates/submit.html
{%extends "layout.html"%}
{%block content%}

    <div class="content-section">
        <h2>Thank you!</h2>
        <p>Your response has been recorded</p>
        
        <div class="border-top pt-3">
            <small class="text-muted">
                Want to make another selection? <a class="ml-2" href="{{url_for('main.home')}}">Homepage</a>
            </small>
        </div>
        
    </div>
    
{%endblock content%}